# Welcome to Jekyll!
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Voltstro
email: me@voltstro.dev
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the home of Voltstro. Here you can find blog posts and other info
  related to me!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://voltstro.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Voltstro"
      layout: post
      show_sidebar: true

# Exclude from processing.
exclude:
  - "[year]-[month]-[day]-post-template.markdown"